### ISSUE TITLE
Write example code

### ISSUE THREAD

**Issue by TuleSimon** [kosher9/Compose_Nice_CheckBox#1]
you should write an example code on how to create the composable, all u did was added a video and the dependency link, how do your users actually create the circular checkbox??

**Comment by kosher9** [comment]
Hi @TuleSimon , how are you doing? Have you taken a look at the [example](https://github.com/kosher9/Compose-Round-CheckBox/blob/main/app/src/main/java/com/kosher9/app/MainActivity.kt)? There you can see the different implementations I've made in the video. :wink:

**Comment by TuleSimon** [comment]
That's the point, people won't have the time to start searching through example code.. it's why all libraries normally have a minimal example of how to instantiate the composable, u can check other libraries to understand what am talking about, it saves our time

**Comment by kosher9** [comment]
Oh, I get it. Let me fix that.
@TuleSimon I updated the Readme file. Please tell me what you think now.

**Comment by TuleSimon** [comment]
Perfect bro.
